version: '3.7'
services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04'
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "z276DtAfs5d!sfn459ndej"
# dotnet-ef dbcontext Scaffold 'Data Source=localhost,1433; Initial Catalog=s17738; User ID=sa;Password=z276DtAfs5d!sfn459ndej' Microsoft.EntityFrameworkCore.SqlServer -o OrmModels
