version: '3.7'
services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04'
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'my_secret_password'